system("wget https://cran.r-project.org/src/contrib/pbkrtest_0.4-6.tar.gz")
system("wget https://cran.r-project.org/src/contrib/quantreg_5.26.tar.gz")
system("wget https://cran.r-project.org/src/contrib/lme4_1.1-12.tar.gz")
system("wget https://cran.r-project.org/src/contrib/minqa_1.2.4.tar.gz")
system("wget https://cran.r-project.org/src/contrib/nloptr_1.0.4.tar.gz")
system("wget https://cran.r-project.org/src/contrib/RcppEigen_0.3.2.8.1.tar.gz")
install.packages("minqa_1.2.4.tar.gz")
install.packages("nloptr_1.0.4.tar.gz")
install.packages("RcppEigen_0.3.2.8.1.tar.gz")
install.packages("lme4_1.1-12.tar.gz")
install.packages("pbkrtest_0.4-6.tar.gz")
install.packages("quantreg_5.26.tar.gz")
