BiocManager::install("ChIPseeker")
BiocManager::install("SeqPlots")
BiocManager::install("Genomation")

BiocManager::install("ggthemes")
BiocManager::install("ggsci")
BiocManager::install("dplyr")
BiocManager::install("reshape")
BiocManager::install("readxl")
BiocManager::install("readr")

source("http://bioconductor.org/biocLite.R")
biocLite("ggthemes")
biocLite("ggsci")
biocLite("dplyr")
biocLite("reshape")
biocLite("readr")
biocLite("readxl")
