install.packages("BH_1.60.0-2.tar.gz")                                                                            
install.packages("diptest_0.75-7.tar.gz")                                                                        
install.packages("dplyr_0.5.0.tar.gz")                                                                        
install.packages("flexmix_2.3-13.tar.gz")                                                                       
install.packages("Hmisc_3.17-4.tar.gz")                                                                           
install.packages("kernlab_0.9-24.tar.gz")                                                                          
install.packages("lyne_0.1.3.tar.gz")                                                                           
install.packages("metilene_v02-6.tar.gz" )                                                                         
install.packages("modeltools_0.2-21.tar.gz")                                                                       
install.packages("prabclus_2.2-6.tar.gz")                                                                       
install.packages("robustbase_0.92-6.tar.gz" )                                                                      
install.packages("segmented_0.5-1.4.tar.gz")                                                                     
install.packages("trimcluster_0.1-2.tar.gz")                                                                     
install.packages("useful_1.2.1.tar.gz")                                                                      
source("http://bioconductor.org/biocLite.R")
library(devtools)
install_github("satijalab/seurat")
library("Seurat")
