BiocManager::install("clusterProfiler", version = "3.8")
BiocManager::install("ReactomePA", version = "3.8")
BiocManager::install("urltools", version = "3.8")
BiocManager::install("backports", version = "3.8")
BiocManager::install("clusterProfiler", version = "3.8")
BiocManager::install("igraph", version = "3.8")
BiocManager::install("fgsea", version = "3.8")
BiocManager::install("DOSE", version = "3.8")
BiocManager::install("ggraph", version = "3.8")
BiocManager::install("enrichplot", version = "3.8")
BiocManager::install("doing", version = "3.8")
BiocManager::install("data.table", version = "3.8")
library("devtools")
library("backports")
library("fgsea")
library("ReactomePA")
library("clusterProfiler")
library("org.Hs.eg.db")
library("DOSE")
library("ReactomePA")

data(geneList)
head(geneList)
de <- names(geneList)[abs(geneList) > 1.5]
de <-c("4312","8318","10874","55143","55388","991")
x <- enrichPathway(gene=de,pvalueCutoff=0.05, readable=T)
barplot(x, showCategory=8)
dotplot(x, showCategory=15)
emapplot(x)
cnetplot(x, categorySize="pvalue", foldChange=geneList)



y <- gsePathway(geneList, nPerm=10000,pvalueCutoff=0.2,pAdjustMethod="BH", verbose=FALSE)
res <- as.data.frame(y)
head(res)
emapplot(y, color="pvalue")
gseaplot(y, geneSetID = "R-HSA-69242")
viewPathway("E2F mediated regulation of DNA replication", readable=TRUE, foldChange=geneList)

