#!/bin/csh
#PBS -N SRR1648425.job
#PBS -q hotel
#PBS -l nodes=1:ppn=8
#PBS -l walltime=167:00:00
#PBS -o SRR1648425.log
#PBS -e SRR1648425.err
#PBS -V
#PBS -M shihcheng.guo@gmail.com 
#PBS -m abe
#PBS -A k4zhang-group
cd /media/Home_Raid1/shg047/work/Chen2016CellResearch/fastq
trim_galore --paired --phred33 --fastqc --illumina SRR1648425_1.fastq.gz SRR1648425_2.fastq.gz --output_dir ../fastq_trim
bismark --bowtie2 --multicore 2 --phred33-quals --fastq -L 25 -N 1 /media/Home_Raid1/shg047/db/hg19/bismark -1 ../fastq_trim/SRR1648425_1_val_1.fq.gz -2 ../fastq_trim/SRR1648425_2_val_2.fq.gz -o ../bam
filter_non_conversion --paired ../bam/SRR1648425_1_val_1_bismark_bt2_pe.bam
samtools sort ../bam/SRR1648425_1_val_1_bismark_bt2_pe.nonCG_filtered.bam -o ../sortbam/SRR1648425_bismark_bt2_pe.sort.bam
samtools index ../sortbam/SRR1648425_bismark_bt2_pe.sort.bam
bismark_methylation_extractor --pair-end --bedGraph --ignore 3 --buffer_size 4G --zero_based --comprehensive --output ../methyfreq  ../bam/SRR1648425_1_val_1_bismark_bt2_pe.nonCG_filtered.bam
