setwd("//mcrfnas2/bigdata/Genetic/Projects/shg047/methylation/HCC")
source("https://raw.githubusercontent.com/Shicheng-Guo/Gscutility/master/assess.R")
data<-read_xlsx("ROC.xlsx",sheet=1)
data<-na.omit(data.frame(data))
dim(data)

model.glm1 <- (bayesglm(Phen ~ Sex+Age,family=binomial,data=data,na.action=na.omit))
model.glm2 <- (bayesglm(Phen ~ Sex+Age+ALT+AST+Tbil,family=binomial,data=data,na.action=na.omit))
model.glm3 <- (bayesglm(Phen ~ Sex+Age+AFP,family=binomial,data=data,na.action=na.omit))
model.glm4 <- (bayesglm(Phen ~ Sex+Age+WGBS,family=binomial,data=data,na.action=na.omit))
model.glm5 <- (bayesglm(Phen ~ Sex+Age+AFP+WGBS,family=binomial,data=data,na.action=na.omit))

library("PredictABEL")
pred1 <- predRisk(model.glm1)
pred2 <- predRisk(model.glm2)
pred3 <- predRisk(model.glm3)
pred4 <- predRisk(model.glm4)
pred5 <- predRisk(model.glm5)
length(pred1)
length(pred2)
length(pred3)
length(pred4)
length(pred5)

par(cex.lab=1.5,cex.axis=1.5,lwd=1.5)
plotROC(data=data,cOutcome=3,predrisk=cbind(pred1,pred2,pred3,pred4,pred5))
legend("bottomright",cex=1.5,legend=c("Sex+Age","Sex+Age+ALT+AST+Tbil","Sex+Age+AFP","Sex+Age+WGBS","Sex+Age+AFP+WGBS"),lty=1:5,col=1:5,bty="n")


model.glm1 <- (bayesglm(Phen ~ AFP,family=binomial,data=data,na.action=na.omit))
model.glm2 <- (bayesglm(Phen ~ WGBS,family=binomial,data=data,na.action=na.omit))
model.glm3 <- (bayesglm(Phen ~ AFP+WGBS,family=binomial,data=data,na.action=na.omit))

library("PredictABEL")
pred1 <- predRisk(model.glm1)
pred2 <- predRisk(model.glm2)
pred3 <- predRisk(model.glm3)
length(pred1)
length(pred2)
length(pred3)

par(cex.lab=1.5,cex.axis=1.5,lwd=1.5)
plotROC(data=data,cOutcome=3,predrisk=cbind(pred1,pred2,pred3))
legend("bottomright",cex=1.5,legend=c("AFP","WGBS","AFP+WGBS"),lty=1:5,col=1:5,bty="n")
