cd /gpfs/home/guosa/hpc/rheumatology/RA/he2019/impute
mkdir temp
for i in {1..22}
do
echo \#PBS -N $i  > $i.job
echo \#PBS -l nodes=1:ppn=1 >> $i.job
echo \#PBS -M Guo.shicheng\@marshfieldresearch.org >> $i.job
echo \#PBS -m abe  >> $i.job
echo \#PBS -o $(pwd)/temp/ >>$i.job
echo \#PBS -e $(pwd)/temp/ >>$i.job
echo cd $(pwd) >> $i.job
echo tabix -f -p vcf chr$i.phased.vcf.gz >> $i.job
echo bcftools view chr$i.phased.vcf.gz -R MUC.hg19.bed -Ov -o MUC.chr$i.vcf
qsub $i.job
done


for i in {1..22}
do
tabix -p vcf chr$i.dose.vcf.gz &
done




