executable = bismark_genome_preparation 
arguments = /home/nu_guos/db/hg19
should_transfer_files = IF_NEEDED
transfer_input_files = hg19.fa
when_to_transfer_output = ON_EXIT
log = $(job)_$(Cluster).log
output = $(job)_$(Cluster)_$(Process).out
error = $(job)_$(Cluster)_$(Process).err
request_cpus = 12
request_memory = 20480MB
request_disk = 20480MB
queue 1

executable = run-test.sh
should_transfer_files = IF_NEEDED
when_to_transfer_output = ON_EXIT
log = $(job)_$(Cluster).log
output = $(job)_$(Cluster)_$(Process).out
error = $(job)_$(Cluster)_$(Process).err
request_cpus = 12
request_memory = 20480MB
request_disk = 20480MB
queue 3


#The below file will run a single job targeting a machine with 16 cores andat least
# 127 GB RAM, with the shared Gluster file system, and will guarantee 72 hours of runtime.
job = spades_test
universe = vanilla
log = $(job)_$(Cluster).log
executable = /bin/sleep
arguments = 7200
output = $(job)_$(Cluster)_$(Process).out
error = $(job)_$(Cluster)_$(Process).err
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = /home/jkwan2/bin/usearch61,Sponges_qiime_A_combined.fasta,Sponges_qiime_KS_combined.fasta
#transfer_output_files = dir.list
request_cpus = 1
# Memory in MBs
request_memory = 16000
# Disk space in KBs
request_disk = 10000000
requirements = (Target.IsDedicated == true) && (Target.HasGluster == true)
queue 1
